/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticeBoardIndexRouteImport } from './routes/notice-board/index'
import { Route as NoticeBoardCreateRouteImport } from './routes/notice-board/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeBoardIndexRoute = NoticeBoardIndexRouteImport.update({
  id: '/notice-board/',
  path: '/notice-board/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeBoardCreateRoute = NoticeBoardCreateRouteImport.update({
  id: '/notice-board/create',
  path: '/notice-board/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notice-board/create': typeof NoticeBoardCreateRoute
  '/notice-board': typeof NoticeBoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notice-board/create': typeof NoticeBoardCreateRoute
  '/notice-board': typeof NoticeBoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notice-board/create': typeof NoticeBoardCreateRoute
  '/notice-board/': typeof NoticeBoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notice-board/create' | '/notice-board'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notice-board/create' | '/notice-board'
  id: '__root__' | '/' | '/notice-board/create' | '/notice-board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoticeBoardCreateRoute: typeof NoticeBoardCreateRoute
  NoticeBoardIndexRoute: typeof NoticeBoardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice-board/': {
      id: '/notice-board/'
      path: '/notice-board'
      fullPath: '/notice-board'
      preLoaderRoute: typeof NoticeBoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice-board/create': {
      id: '/notice-board/create'
      path: '/notice-board/create'
      fullPath: '/notice-board/create'
      preLoaderRoute: typeof NoticeBoardCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoticeBoardCreateRoute: NoticeBoardCreateRoute,
  NoticeBoardIndexRoute: NoticeBoardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
